FROM richarvey/nginx-php-fpm:3.1.6

COPY . .

# Image & Webroot Configuration
ENV WEBROOT /var/www/html/public
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

# Allow composer as root
ENV COMPOSER_ALLOW_SUPERUSER 1

# Install frontend dependencies and build assets
RUN npm install && npm run build